using TMPro;
using UnityEngine;

public class RandomDeathMessage : MonoBehaviour
{
    public TMP_Text deathText;

    private string[] deathMessages = {
        "You have drowned in the ocean after surviving for {0} seconds.",
        "The ocean has claimed another life after {0} seconds.",
        "Your journey to the depths of the sea has ended after surviving for {0} seconds.",
        "You have been lost to the vastness of the sea after surviving for {0} seconds.",
        "The underwater world has claimed another explorer after surviving for {0} seconds.",
        "You were unable to resist the ocean's force after surviving for {0} seconds.",
        "The sea's relentless power has taken another victim after surviving for {0} seconds.",
        "You have become a permanent resident of the ocean's depths after surviving for {0} seconds.",
        "The underwater world has claimed yet another adventurer after surviving for {0} seconds.",
        "You were unable to conquer the ocean's power after surviving for {0} seconds.",
        "The ocean's mysteries have claimed another curious explorer after surviving for {0} seconds.",
        "You have become another casualty of the sea after surviving for {0} seconds.",
        "Your adventure in the ocean has come to a deadly end after surviving for {0} seconds.",
        "The ocean's vastness proved too much for you to handle after surviving for {0} seconds.",
        "You have been claimed by the sea after surviving for {0} seconds.",
        "The underwater world has taken its toll on you after surviving for {0} seconds.",
        "You were unable to escape the ocean's grip after surviving for {0} seconds.",
        "Your journey to the depths of the sea has come to a tragic end after surviving for {0} seconds.",
        "The ocean's creatures have claimed another victim after {0} seconds.",
        "You have become one with the sea after surviving for {0} seconds.",
        "You have become one with the ocean after surviving for {0} seconds.",
        "The sea's unrelenting power has taken you after surviving for {0} seconds.",
        "Your fate has been sealed by the ocean's depths after surviving for {0} seconds.",
        "You were unable to resist the ocean's call after surviving for {0} seconds.",
        "The underwater world has swallowed you whole after surviving for {0} seconds.",
        "You have met your end in the depths of the ocean after surviving for {0} seconds.",
        "The ocean's currents have taken you away after surviving for {0} seconds.",
        "Your journey to the unknown depths of the ocean has ended after surviving for {0} seconds.",
        "The sea's unforgiving nature has claimed another victim after surviving for {0} seconds.",
        "You have been lost to the vastness of the sea after surviving for {0} seconds.",
       "The ocean's secrets have claimed another life after {0} seconds.",
        "You were unable to withstand the ocean's power after surviving for {0} seconds.",
        "The underwater world has taken another soul after surviving for {0} seconds.",
        "You have been consumed by the sea after surviving for {0} seconds.",
        "The ocean's depths proved too treacherous for you after surviving for {0} seconds.",
        "Your adventure in the ocean has come to a tragic end after surviving for {0} seconds.",
        "The sea's force has taken you after surviving for {0} seconds.",
        "You were unable to escape the ocean's clutches after surviving for {0} seconds.",
        "The underwater world has claimed another victim after surviving for {0} seconds.",
        "You have become lost in the ocean's vastness after surviving for {0} seconds.",
        "The ocean's mysteries have claimed another life after surviving for {0} seconds.",
        "You were unable to withstand the ocean's pressure after surviving for {0} seconds.",
        "The sea's unyielding power has taken you after surviving for {0} seconds.",
        "Your journey to the depths of the ocean has come to a deadly end after surviving for {0} seconds.",
        "The ocean's inhabitants have claimed another victim after surviving for {0} seconds.",
        "You have become another tragic story of the ocean after surviving for {0} seconds.",
        "The sea's currents have taken you away after surviving for {0} seconds.",
        "You were unable to outswim the ocean's power after surviving for {0} seconds.",
        "The underwater world has swallowed you up after surviving for {0} seconds.",
        "You have met your demise in the ocean's depths after surviving for {0} seconds.",
        "The ocean's vastness ultimately proved insurmountable after surviving for {0} seconds.",
        "You survived for {0} seconds, but the ocean's vastness proved too much to overcome.",
        "You were unable to escape the ocean's wrath after surviving for {0} seconds.",
        "The underwater world has taken its toll on you after surviving for {0} seconds.",
        "You have become a victim of the sea's unforgiving nature after surviving for {0} seconds.",
        "The ocean's power has overcome you after surviving for {0} seconds.",
        "Your journey to the unknown depths of the ocean has ended tragically after surviving for {0} seconds.",
        "The sea's unpredictability has claimed another life after surviving for {0} seconds.",
        "You have succumbed to the ocean's force after surviving for {0} seconds.",
        "You survived for {0} seconds.",
        "{0} seconds are nothing compared to the endless depths of the ocean.",
        "Your lifespan was very short: {0} seconds.",
        "You died after surviving for {0} seconds.",
        "{0} seconds are like an ocean breeze.",
        "The ocean's immensity bested you, despite your brave {0}-second struggle.",
        "Your resilience was no match for the unfathomable depths of the ocean, as you survived only {0} seconds.",
        "The mighty ocean overpowered you after {0} seconds of valiant effort.",
        "Despite your best efforts, the ocean's enormity proved too much to endure after {0} seconds.",
        "Your bravery in facing the ocean's vastness lasted {0} seconds before ultimately succumbing.",
        "After surviving for {0} seconds, the ocean's boundless magnitude proved insurmountable.",
        "The ocean proved an unrelenting opponent, overwhelming you after {0} seconds of struggle.",
        "For {0} seconds, you challenged the ocean's infinite power, but it proved too much to bear.",
        "Despite your courage and endurance, the vastness of the ocean proved unconquerable after {0} seconds.",
        "As a gentle jellyfish, you danced through the ocean's currents for {0} seconds, until it swallowed you whole.",
        "For {0} seconds, you floated gracefully in the ocean. But not any longer.",
        "The ocean's embrace was too much for a delicate jellyfish like you, as it claimed you after {0} seconds.",
        "You became one with the ocean after {0} seconds.",
        "You became one with the depths of the sea after {0} seconds.",
        "You wandered the ocean's blue expanse for {0} seconds, before disappearing into its depths.",
        "The ocean's beauty enticed you for {0} seconds, before it finally took you in its grasp.",
        "You swam through the ocean's currents for {0} seconds, until it claimed you as its own.",
        "For {0} seconds, you glided through the ocean's clear waters, until it decided to take you to its depths.",
        "As a small jellyfish, you floated through the ocean's mysteries for {0} seconds, until it called you home.",
        "Your brave journey through the ocean's depths came to an end after {0} seconds of exploration.",
        "Despite your valiant efforts, the ocean's mysteries proved too much to bear after surviving for {0} seconds.",
        "Your adventure through the vastness of the ocean lasted for {0} seconds, until it claimed you as its own.",
        "For {0} seconds, you journeyed through the sea, until it decided it was time for you to leave.",
        "As a fearless explorer of the ocean, your journey ended after {0} seconds of discovery.",
        "The ocean's infinite wonders proved too much to handle after {0} seconds of exploration.",
        "Your journey through the ocean's secrets was cut short after {0} seconds of discovery.",
        "As an adventurer of the deep, your journey through the ocean lasted for {0} seconds before coming to an end.",
        "The ocean's vastness swallowed you whole after {0} seconds of exploration and discovery.",
        "Despite your efforts to brave the ocean's depths, it claimed you after surviving for {0} seconds.",
        "For {0} seconds, you explored the ocean's wonders, until it decided to take you into its embrace.",
        "As a brave traveler through the sea, your journey ended after {0} seconds of exploration and discovery.",
        "The ocean's power was too great, as it claimed you after surviving for {0} seconds.",
        "Your journey through the mysteries of the ocean came to an end after {0} seconds of exploration and wonder.",
        "Despite your courage, the ocean's depth proved too much to bear after surviving for {0} seconds.",
    };

    private void OnEnable()
    {
        RandomizeDeathMessage();
    }

    private void RandomizeDeathMessage()
    {
        int randomIndex = Random.Range(0, deathMessages.Length);
        deathText.text = string.Format(deathMessages[randomIndex], IngameTimer.gameTimer.ToString("0.00"));
    }
}
